### ISSUE TITLE
Do you falsificating benchmark results?

### ISSUE THREAD

**Issue by PukPukov** [LoneDev6/FastNBT-Benchmark#1]
Why even would you run tests before benchmarking? They can affect results via JIT. This is much more suspicious because you forcing to reload test plugin via plugman for every run that, afai understand, should clear everything that JIT compiled and forcing it to compile it again.

**Comment by LoneDev6** [comment]
You're free to do your own benchmarking, I am not here to take over the market with a free plugin so I have no intention to provide false data.

Anyway I am using plugman to reload the benchmark program not the FastNBT plugin itself, so I don't see how the JIT will optimize FastNBT over NBTAPI if the reloaded code is the benchmark one and not the FastNBT code.
